export const customers = [
    {
        id: 'cust-amelia-wong',
        name: 'Amelia Wong',
        email: 'amelia.wong@example.com',
        status: 'Active',
        type: 'Retail',
        totalSpent: 4850,
        lastOrderDate: '2024-02-14',
        orders: [
            {
                date: '2024-02-14',
                items: 'Herb starter kit, nutrient refill',
                total: 950,
                status: 'Delivered',
            },
            {
                date: '2024-01-08',
                items: 'Hydroponic tower',
                total: 1900,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-lars-olsen',
        name: 'Lars Olsen',
        email: 'lars.olsen@example.com',
        status: 'Active',
        type: 'Wholesale',
        totalSpent: 15200,
        lastOrderDate: '2024-03-02',
        orders: [
            {
                date: '2024-03-02',
                items: 'Bulk basil seedlings',
                total: 5200,
                status: 'Processing',
            },
            {
                date: '2024-01-22',
                items: 'Packaging supplies (case)',
                total: 4100,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-sara-nyberg',
        name: 'Sara Nyberg',
        email: 'sara.nyberg@example.com',
        status: 'At risk',
        type: 'Subscriber',
        totalSpent: 2100,
        lastOrderDate: '2023-12-18',
        orders: [
            {
                date: '2023-12-18',
                items: 'Monthly greens subscription',
                total: 700,
                status: 'Delivered',
            },
            {
                date: '2023-11-18',
                items: 'Monthly greens subscription',
                total: 700,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-johan-lind',
        name: 'Johan Lind',
        email: 'johan.lind@example.com',
        status: 'Inactive',
        type: 'Retail',
        totalSpent: 540,
        lastOrderDate: '2023-08-05',
        orders: [
            {
                date: '2023-08-05',
                items: 'Seedling pack',
                total: 540,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-fatima-khan',
        name: 'Fatima Khan',
        email: 'fatima.khan@example.com',
        status: 'Active',
        type: 'Retail',
        totalSpent: 3280,
        lastOrderDate: '2024-03-10',
        orders: [
            {
                date: '2024-03-10',
                items: 'Grow lights, nutrient kit',
                total: 1320,
                status: 'Shipped',
            },
            {
                date: '2024-02-01',
                items: 'Basil seedlings',
                total: 420,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-marcus-berg',
        name: 'Marcus Berg',
        email: 'marcus.berg@example.com',
        status: 'Active',
        type: 'Wholesale',
        totalSpent: 9800,
        lastOrderDate: '2024-02-27',
        orders: [
            {
                date: '2024-02-27',
                items: 'Bulk grow media',
                total: 3600,
                status: 'Delivered',
            },
            {
                date: '2024-01-12',
                items: 'Hydroponic racks',
                total: 4200,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-emma-svensson',
        name: 'Emma Svensson',
        email: 'emma.svensson@example.com',
        status: 'Active',
        type: 'Subscriber',
        totalSpent: 1800,
        lastOrderDate: '2024-03-05',
        orders: [
            {
                date: '2024-03-05',
                items: 'Monthly greens subscription',
                total: 600,
                status: 'Processing',
            },
            {
                date: '2024-02-05',
                items: 'Monthly greens subscription',
                total: 600,
                status: 'Delivered',
            },
        ],
    },
    {
        id: 'cust-alex-rahman',
        name: 'Alex Rahman',
        email: 'alex.rahman@example.com',
        status: 'Active',
        type: 'Retail',
        totalSpent: 2600,
        lastOrderDate: '2024-02-20',
        orders: [
            {
                date: '2024-02-20',
                items: 'Starter kit, seed mix',
                total: 980,
                status: 'Delivered',
            },
            {
                date: '2024-01-05',
                items: 'Replacement filters',
                total: 320,
                status: 'Delivered',
            },
        ],
    },
];
